cons_index:
    path:     /
    defaults: { _controller: "ConsultationBundle:Cons:index" }
    methods:  GET

cons_show:
    path:     /{id}/show
    defaults: { _controller: "ConsultationBundle:Cons:show" }
    methods:  GET

cons_new:
    path:     /new
    defaults: { _controller: "ConsultationBundle:Cons:new" }
    methods:  [GET, POST]

cons_edit:
    path:     /{id}/edit
    defaults: { _controller: "ConsultationBundle:Cons:edit" }
    methods:  [GET, POST]

cons_delete:
    path:     /{id}/delete
    defaults: { _controller: "ConsultationBundle:Cons:delete" }
    methods:  DELETE
